#!/usr/bin/env ruby

# TODO: maybe completion could pass along a TABRY_PATH here? so we wouldn't
# have to run bundler until after the config block
require_relative '../../lib/tabry/cli/all_in_one.rb'

Tabry::CLI::AllInOne.run do
  config(names_underscores_to_dashes: true) do
    completion

    sub :things do
      sub 'list,l', "List the things"
      sub 'add,a' do
        arg :thing_name
      end
      sub 'delete, d', :@thing_name
      sub 'rename, move, mv', :@thing_name do
        arg :new_thing_name
      end
    end

    defargs :@thing_name do
      arg :thing_name do
        opts shell "hello things list"
      end
    end
  end

  # You can but requires here if the may be expensive; things here will not get
  # run if running completion only
  def things__list = puts(%w[foo bar waz])
  def things__add = puts("adding #{args.thing_name}")
  def things__delete = puts("deleting #{args.thing_name}")
  def things__rename = puts("renameing #{args.thing_name}")
end

# One less level of "all-in-one-ness" is separating out the config, which is
# good for code organization:
#
# module MyCli
#   TabryConfig = Tabry::CLI::ConfigBuilder.build do
#     completion
#     sub ...
#   en
# end
#
# Tabry::CLI::AllInOne.ruin(config: TabryConfig) do
# end
# ...
#
#
# Tabry::CLI::AllInOne will detect the "completion" sub in the config and
# make the methods to generate bash completion and to actually run completion
# (with just "completion").
#
# However this still has the problem of it being potentially slow to run the
# completion as it probably needs to use bundler to run your "cli completion"
# command and load tabry. A better option is to use the hash generated
# ConfigBuilder.build and write it to a YML/JSON file and use make a completion__bash
# command to generate a completion which uses the YML/JSON file.
#
# TODO: I hope to make this a little easier to use soon so generate_bash can
# make config which uses a ruby file (which only has the
# Tabry::ConfigBuilder.build command) instead of a YML file, and some helper
# methods to tie this all together (e.g. something to create the
# completion__bash method in the CLI which does the right thing, and create
# the "completion bash" but not "completion" commands in the Tabry config)
#
