# frozen_string_literal: true

# Used to generate a tab-completion function for a Tabry CLI using absolute
# paths to the tabry-bash script in this repo and to the Tabry JSON/YML file.
# Using uniquely-named tab-completion functions and absolute paths means you can
# have different Tabry-based CLIs using different versions of Tabry without any
# conflicts.
# See sh/bash/README.md and "Adding Tab Completion to your CLI" in main README

require "shellwords"

module Tabry
  module Shells
    module Bash
      # NOTE! This code uses sh/bash/tabry_bash_core.sh and is described in
      # sh/bash/README.md; see that README for more info
      def self.generate(cmd_name, tabry_file_path, uniq_fn_id: nil, ruby_path: nil)
        ruby_path ||= "ruby"
        generate_internal(
          cmd_name: cmd_name,
          import_path: Shellwords.escape(File.expand_path(tabry_file_path)),
          tabry_bash_executable: ruby_path,
          tabry_bash_arg: Shellwords.escape("#{path_to_tabry}/bin/tabry-bash"),
          uniq_fn_id: uniq_fn_id
        )
      end

      # Generate bash completion code that will run the currently running
      # command ($0) with "completion" to get completion options. "cmd_name"
      # is used to tell bash which command to make options for (and
      # for naming of the _tabry_CMD_NAME_completions_internal bash function)
      def self.generate_self(cmd_name: nil)
        cmd_name ||= File.basename($0)
        generate_internal(
          cmd_name: cmd_name,
          import_path: "",
          tabry_bash_executable: File.expand_path($0),
          tabry_bash_arg: "completion"
        )
      end

      def self.path_to_tabry
        Shellwords.escape(File.expand_path("#{__dir__}/../../../"))
      end

      def self.generate_internal(cmd_name:, import_path:, tabry_bash_executable:, tabry_bash_arg:, uniq_fn_id: nil)
        # uniq_fn_id is added to the bash functions to ensure they are unique
        # -- by default this is the capitalized command name
        uniq_fn_id ||= cmd_name.upcase.gsub(/[^a-zA-Z0-9_]/, "_")
        core = File.read("#{__dir__}/../../../sh/bash/tabry_bash_core.sh")
        core.gsub! "_tabry_completions_internal()", "_tabry_#{uniq_fn_id}_completions_internal()"

        <<~END_BASH_CODE_TEMPLATE + core
          # The following Autocomplete is for a Tabry-powered command. It was
          # generated by the command itself. See the documentation located in
          # #{path_to_tabry}/sh/bash/README.md
          _tabry_#{uniq_fn_id}_completions() {
            TABRY_IMPORTS_PATH=#{import_path} _tabry_#{uniq_fn_id}_completions_internal #{tabry_bash_executable} #{tabry_bash_arg}
          }
          complete -F _tabry_#{uniq_fn_id}_completions #{Shellwords.escape cmd_name}
        END_BASH_CODE_TEMPLATE
      end
    end
  end
end
